language: JavaScript

branches:
  only:
    - master

before_script:
  - echo `pwd`
  - tar -xzf sdk/ext.tgz -C .
  - tar -xzf sdk/cmd.tgz -C .
  - export PATH=`pwd`/cmd/:$PATH
  - export SENCHA_CMD_3_0_0=`pwd`/cmd/
  - npm install codeclimate-test-reporter
  - export PATH=`pwd`/node_modules/.bin/:$PATH
  - sencha diag show
  - sencha app build
#  - sencha web -p 1841 start &
#  - sleep 20
  - java -jar app-test/lib/jscover/JSCover-all.jar -ws --document-root=. --report-dir=app-test/report --no-instrument=app-test --no-instrument=ext &
  - sleep 5

script:
#  - phantomjs app-test/phantom-jasmine.js http://localhost:1841/app-test/run-tests.html
  - phantomjs app-test/phantom-jasmine.js http://localhost:8080/app-test/run-tests.html

after_script:
#  - sencha web -p 1841 stop
  - java -cp app-test/lib/jscover/JSCover-all.jar jscover.report.Main --format=LCOV app-test/report/phantom/ app-test/report/phantom/original-src/
  - cd app-test/report/phantom/original-src/
  - codeclimate < ../jscover.lcov

addons:
  code_climate:
    repo_token:
      secure: "gVfj6HKajImimelhrVCBRXeeSN793G6/PcFVSplUZ4rGjQj2wU488XT8ervxElWC8/qNURgLRBrxOt7NkjU3XMTxF+8+wXMPBhV5wYTC+EY1bMo695Bm6STM7rd1Pxic58OUzidUwbgvk/xbnGVE38U1w8R0A/38tbQbEZeZFnc="

notifications:
  email:
    recipients:
      - shamanu4+travis.moneypot-ui@gmail.com
