language: JavaScript

branches:
  only:
    - master

before_script:
  - echo `pwd`
  - tar -xzf sdk/ext.tgz -C .
  - tar -xzf sdk/cmd.tgz -C .
  - export PATH=`pwd`/cmd/:$PATH
  - export SENCHA_CMD_3_0_0=`pwd`/cmd/
  - sencha diag show
  - sencha app build
  - npm install codeclimate-test-reporter
#  - sencha web -p 1841 start &
#  - sleep 20
  - java -jar app-test/lib/jscover/JSCover-all.jar -ws --document-root=. --report-dir=app-test/report --no-instrument=app-test --no-instrument=ext

script:
#  - phantomjs app-test/phantom-jasmine.js http://localhost:1841/app-test/run-tests.html
  - phantomjs app-test/phantom-jasmine.js http://localhost:8080/app-test/run-tests.html

after_script:
#  - sencha web -p 1841 stop
  - CODECLIMATE_REPO_TOKEN=30142ca7fcb05b657235b60124a37f8c896bab311e20361a20d2e745c760d6eb node_modules/codeclimate-test-reporter/bin/codeclimate.js < app-test/report/phantom/jscover.lcov

notifications:
  email:
    recipients:
      - shamanu4+travis.moneypot-ui@gmail.com